version: '3'

env:
  ENV: dev
  COMPOSE_PROJECT_NAME: sai708th-dotfiles

tasks:
  list:
    dir: .
    cmds:
      - task --list-all
  nvim:build:
    dir: dotfiles
    cmds: 
      - docker image build -t sai708th/dotfiles:nvim --platform=linux/arm64 --no-cache .
  nvim:run:
    dir: dotfiles
    cmds:
      - docker run --rm -it --platform linux/arm64 sai708th/dotfiles:nvim zsh
  nvim:run2:
    dir: dotfiles
    cmds:
      - docker run --rm -it --platform linux/amd64 --no-cache sai708th/dotfiles:nvim zsh
  rtty:run:
    dir: rtty
    cmds:
      - docker compose run -d rtty
      - docker compose exec rtty /go/bin/rtty run zsh -p 10000 --addr 0.0.0.0 --font 'Monaco' --font-size 16
  rtty:down:
    dir: rtty
    cmds:
      - docker compose down
  rvljs:up:
    #https://qiita.com/uphy/items/61e875f97bbb58a75beb
    dir: reveal.js
    cmds:
      - docker compose up -d
  rvljs:down:
    #https://qiita.com/uphy/items/61e875f97bbb58a75beb
    dir: reveal.js
    cmds:
      - docker compose down
