version: '3'

env:
  ENV: dev
  COMPOSE_PROJECT_NAME: sai708th-dotfiles

tasks:
  list:
    dir: .
    cmds:
      - task --list-all
  nvim:build:
    dir: dotfiles
    cmds: 
      - docker image build -t sai708th/dotfiles:nvim --platform=linux/arm64 --no-cache .
  nvim:run:
    dir: dotfiles
    cmds:
      - docker run --rm -it --platform linux/arm64 sai708th/dotfiles:nvim zsh
  nvimrtty:build:
    dir: nvim_rtty
    cmds: 
      - docker compose build --no-cache nvim_rtty
  nvimrtty:run:
    dir: nvim_rtty
    cmds:
      - docker compose run -p 10000:10000 nvim_rtty
  rtty:build:
    dir: rtty
    cmds: 
      - docker image build -t sai708th/rtty:base --platform=linux/arm64 --no-cache .
  rtty:run:
    dir: rtty
    cmds:
      - docker compose run -p 10000:10000 rtty
  rvljs:up:
    #https://qiita.com/uphy/items/61e875f97bbb58a75beb
    dir: reveal.js
    cmds:
      - docker compose up -d
  rvljs:down:
    #https://qiita.com/uphy/items/61e875f97bbb58a75beb
    dir: reveal.js
    cmds:
      - docker compose down


#rb:
#  dir: .
#  cmds:
#    - docker compose build
#up:
#  dir: .
#  cmds:
#    - docker compose up -d
#dn:
#  dir: .
#  cmds:
#    - docker compose down
