version: '3'

env:
  ENV: dev
  COMPOSE_PROJECT_NAME: sai708th-dotfiles

tasks:
  list:
    dir: .
    cmds:
      - task --list-all
  nvim:build:
    dir: dotfiles
    cmds: 
      - docker image build -t sai708th/dotfiles:nvim --platform=linux/arm64 --no-cache .
  nvim:run:
    dir: dotfiles
    cmds:
      - docker run --rm -it --platform linux/arm64 sai708th/dotfiles:nvim zsh

  wpup:
    dir: wordpress
    cmds:
      - docker compose up -d
  wpdn:
    dir: wordpress
    cmds:
      - docker compose down -v
  wpin:
    dir: wordpress
    cmds:
      - docker exec -it -w /var/www/html/wp-content wordpress bash

#rb:
#  dir: .
#  cmds:
#    - docker compose build
#up:
#  dir: .
#  cmds:
#    - docker compose up -d
#dn:
#  dir: .
#  cmds:
#    - docker compose down
