version: '3.9'

services:
  nvim_rtty:
    platform: linux/arm64
    build:
        context: .
        dockerfile: Dockerfile
    image: sai708th/rtty:nvim
    command: ["zsh", "-ic", "/root/go/bin/rtty run zsh -p 10000 --addr 0.0.0.0 --font 'Monaco' --font-size 16"]
    ports:
      - "10000:10000"
    volumes:
      - type: bind
        source: ~/Dev
        target: /root/Dev

