version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: wordpress.df
    ports:
      - "8081:80"   
      - "8443:443" 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress_data:/var/www/html
      - ./wp/wp-config.php:/var/www/html/wp-config.php  # wp-config.phpをバインドマウント
      - ./wp/wp-content:/var/www/html/wp-content  # wp-contentディレクトリをバインドマウント
    networks:
      - wordpress_network

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_network:
