version: '3.9'

services:
  rtty:
    platform: linux/arm64
    build:
        context: .
        dockerfile: Dockerfile
    command: ["zsh", "-ic", "/go/bin/rtty run zsh -p 10000 --addr 0.0.0.0 --font 'Monaco' --font-size 16"]
    ports:
      - "10000:10000"

